# theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
remote_theme: "mmistakes/minimal-mistakes@4.11.2"
minimal_mistakes_skin: "mint" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

include: 
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false


# Site Settings
url: "https://mechanicalkeyboardsgreece.github.io"
baseurl: "/info-guide"
repository: "MechanicalKeyboardsGreece/info-guide"
locale: "el-GR"
title: "Mechanical Keyboards Greece"
description: Οδηγός γενικών πληροφοριών για το facebook group "Mechanical Keyboards Greece"